# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="mynij-proxy",
    version="0.1.0",
    python_requires="==3.*,>=3.9.0",
    author="Stefane Fermigier",
    author_email="sf@fermigier.com",
    packages=[],
    package_dir={"": "src"},
    package_data={},
    install_requires=[
        "gunicorn==20.*,>=20.1.0",
        "httptools",
        "httpx==0.*,>=0.18.1",
        "starlette==0.*,>=0.14.2",
        "uvicorn==0.*,>=0.13.4",
        "uvloop==0.*,>=0.15.2",
    ],
    extras_require={
        "dev": [
            "black==21.*,>=21.4.0.b2",
            "honcho",
            "isort==5.*,>=5.8.0",
            "pytest==6.*,>=6.2.4",
            "requests==2.*,>=2.25.1",
        ]
    },
)
